version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nbddb
      POSTGRES_USER: nbd
      POSTGRES_PASSWORD: nbd
    ports:
      - 5001:5432
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
